import { useMemo } from 'react';

import { type LottieColor } from '../../../helpers/convert-lottie-color-to-rgb';

const useGetLoaderJSON = (color: LottieColor) => {
  return useMemo(() => {
    return {
      nm: 'loader-check',
      ddd: 0,
      h: 64,
      w: 64,
      meta: { g: '@lottiefiles/creator 1.14.0' },
      layers: [
        {
          ty: 4,
          nm: 'loader',
          sr: 1,
          st: 0,
          op: 120,
          ip: 0,
          hd: false,
          ddd: 0,
          bm: 0,
          hasMask: false,
          ao: 0,
          ks: {
            a: { a: 0, k: [0, 0, 0], ix: 1 },
            s: { a: 0, k: [100, 100, 100], ix: 6 },
            sk: { a: 0, k: 0 },
            p: { a: 0, k: [32, 32, 0], ix: 2 },
            r: {
              a: 1,
              k: [
                {
                  o: { x: 0.167, y: 0.167 },
                  i: { x: 0.833, y: 0.833 },
                  s: [0],
                  t: 0,
                },
                {
                  s: [1440],
                  t: 96,
                },
              ],
              ix: 10,
            },
            sa: { a: 0, k: 0 },
            o: {
              a: 1,
              k: [
                { o: { x: 0.333, y: 0 }, i: { x: 0, y: 1 }, s: [100], t: 100 },
                { s: [0], t: 104 },
              ],
              ix: 11,
            },
          },
          shapes: [
            {
              ty: 'gr',
              bm: 0,
              hd: false,
              mn: 'ADBE Vector Group',
              nm: 'Ellipse 1',
              ix: 1,
              cix: 2,
              np: 4,
              it: [
                {
                  ty: 'el',
                  bm: 0,
                  hd: false,
                  mn: 'ADBE Vector Shape - Ellipse',
                  nm: 'Ellipse Path 1',
                  d: 1,
                  p: { a: 0, k: [0, 0], ix: 3 },
                  s: { a: 0, k: [60, 60], ix: 2 },
                },
                {
                  ty: 'tm',
                  bm: 0,
                  hd: false,
                  mn: 'ADBE Vector Filter - Trim',
                  nm: 'Trim Paths 1',
                  ix: 2,
                  e: {
                    a: 1,
                    k: [
                      {
                        o: { x: 0.333, y: 0 },
                        i: { x: 0.667, y: 1 },
                        s: [100],
                        t: 0,
                      },
                      {
                        o: {
                          x: 0.333,
                          y: 0,
                        },
                        i: { x: 0.667, y: 1 },
                        s: [6],
                        t: 61,
                      },
                      { s: [100], t: 96 },
                    ],
                    ix: 2,
                  },
                  o: { a: 0, k: 0, ix: 3 },
                  s: {
                    a: 1,
                    k: [
                      {
                        o: { x: 0.167, y: 0 },
                        i: { x: 0.833, y: 1 },
                        s: [0],
                        t: 0,
                      },
                      {
                        o: {
                          x: 0.174,
                          y: 0,
                        },
                        i: { x: 0.57, y: 1 },
                        s: [80],
                        t: 48,
                      },
                      {
                        o: { x: 0.398, y: 0 },
                        i: { x: 0.839, y: 1 },
                        s: [30],
                        t: 83,
                      },
                      { s: [0], t: 96 },
                    ],
                    ix: 1,
                  },
                  m: 1,
                },
                {
                  ty: 'st',
                  bm: 0,
                  hd: false,
                  mn: 'ADBE Vector Graphic - Stroke',
                  nm: 'Stroke 1',
                  lc: 2,
                  lj: 2,
                  ml: 1,
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 4, ix: 5 },
                  c: { a: 0, k: color, ix: 3 },
                },
                {
                  ty: 'tr',
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  sk: { a: 0, k: 0, ix: 4 },
                  p: { a: 0, k: [0, 0], ix: 2 },
                  r: { a: 0, k: 0, ix: 6 },
                  sa: { a: 0, k: 0, ix: 5 },
                  o: { a: 0, k: 100, ix: 7 },
                },
              ],
            },
          ],
          ind: 1,
        },
        {
          ty: 4,
          nm: 'circle',
          sr: 1,
          st: 0,
          op: 120,
          ip: 0,
          hd: false,
          ddd: 0,
          bm: 0,
          hasMask: false,
          ao: 0,
          ks: {
            a: { a: 0, k: [32, 32, 0], ix: 1 },
            s: { a: 0, k: [100, 100, 100], ix: 6 },
            sk: { a: 0, k: 0 },
            p: { a: 0, k: [32, 32, 0], ix: 2 },
            r: { a: 0, k: 0, ix: 10 },
            sa: { a: 0, k: 0 },
            o: {
              a: 1,
              k: [
                {
                  o: { x: 0.716, y: 0 },
                  i: { x: 0.667, y: 1 },
                  s: [30],
                  t: 100,
                },
                {
                  s: [0],
                  t: 104,
                },
              ],
              ix: 11,
            },
          },
          shapes: [
            {
              ty: 'gr',
              bm: 0,
              hd: false,
              mn: 'ADBE Vector Group',
              nm: 'Group 1',
              ix: 1,
              cix: 2,
              np: 4,
              it: [
                {
                  ty: 'sh',
                  bm: 0,
                  hd: false,
                  mn: 'ADBE Vector Shape - Group',
                  nm: 'Path 1',
                  ix: 1,
                  d: 1,
                  ks: {
                    a: 0,
                    k: {
                      c: true,
                      i: [
                        [-15.464, 0],
                        [0, 15.464],
                        [15.464, 0],
                        [0, -15.464],
                      ],
                      o: [
                        [15.464, 0],
                        [0, -15.464],
                        [-15.464, 0],
                        [0, 15.464],
                      ],
                      v: [
                        [0, 28],
                        [28, 0],
                        [0, -28],
                        [-28, 0],
                      ],
                    },
                    ix: 2,
                  },
                },
                {
                  ty: 'sh',
                  bm: 0,
                  hd: false,
                  mn: 'ADBE Vector Shape - Group',
                  nm: 'Path 2',
                  ix: 2,
                  d: 1,
                  ks: {
                    a: 0,
                    k: {
                      c: true,
                      i: [
                        [17.673, 0],
                        [0, 17.673],
                        [-17.673, 0],
                        [0, -17.673],
                      ],
                      o: [
                        [-17.673, 0],
                        [0, -17.673],
                        [17.673, 0],
                        [0, 17.673],
                      ],
                      v: [
                        [0, 32],
                        [-32, 0],
                        [0, -32],
                        [32, 0],
                      ],
                    },
                    ix: 2,
                  },
                },
                {
                  ty: 'mm',
                  bm: 0,
                  hd: false,
                  mn: 'ADBE Vector Filter - Merge',
                  nm: 'Merge Paths 1',
                  mm: 1,
                },
                {
                  bm: 0,
                  c: { a: 0, k: color, ix: 4 },
                  hd: false,
                  mn: 'ADBE Vector Graphic - Fill',
                  nm: 'Fill 1',
                  o: { a: 0, k: 100, ix: 5 },
                  r: 1,
                  ty: 'fl',
                },
                {
                  ty: 'tr',
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  sk: { a: 0, k: 0, ix: 4 },
                  p: { a: 0, k: [32, 32], ix: 2 },
                  r: { a: 0, k: 0, ix: 6 },
                  sa: { a: 0, k: 0, ix: 5 },
                  o: { a: 0, k: 100, ix: 7 },
                },
              ],
            },
          ],
          ind: 2,
        },
      ],
      v: '5.7.0',
      fr: 24,
      op: 96,
      ip: 0,
      assets: [],
    };
  }, [color]);
};
export default useGetLoaderJSON;
