import { useMemo } from 'react';

import { type LottieColor } from '../../../helpers/convert-lottie-color-to-rgb';

const useGetLoaderSuccessJSON = (color: LottieColor) => {
  return useMemo(() => {
    return {
      nm: 'loader-check',
      ddd: 0,
      h: 64,
      w: 64,
      meta: { g: '@lottiefiles/creator 1.14.0' },
      layers: [
        {
          ty: 0,
          nm: 'check',
          sr: 1,
          st: 0,
          op: 24,
          ip: 0,
          hd: false,
          ddd: 0,
          bm: 0,
          hasMask: false,
          ao: 0,
          ks: {
            a: { a: 0, k: [32, 32, 0], ix: 1 },
            s: { a: 0, k: [100, 100, 100], ix: 6 },
            sk: { a: 0, k: 0 },
            p: { a: 0, k: [0, 0, 0], ix: 2 },
            r: { a: 0, k: 0, ix: 10 },
            sa: { a: 0, k: 0 },
            o: { a: 0, k: 100, ix: 11 },
          },
          w: 64,
          h: 64,
          refId: 'comp_0_dcf4d207-44cc-4b07-a995-b6aca93c84dc',
          ind: 1,
          parent: 2,
        },
        {
          ty: 4,
          nm: 'green circle',
          sr: 1,
          st: -109,
          op: 24,
          ip: 0,
          hd: false,
          ddd: 0,
          bm: 0,
          hasMask: false,
          ao: 0,
          ks: {
            a: { a: 0, k: [0, 0, 0], ix: 1 },
            s: {
              a: 1,
              k: [
                {
                  o: { x: 0.21, y: 0 },
                  i: { x: 0, y: 1 },
                  s: [0, 0, 100],
                  t: 0,
                },
                { s: [100, 100, 100], t: 12 },
              ],
              ix: 6,
            },
            sk: { a: 0, k: 0 },
            p: { a: 0, k: [32, 32, 0], ix: 2 },
            r: { a: 0, k: 0, ix: 10 },
            sa: { a: 0, k: 0 },
            o: { a: 0, k: 100, ix: 11 },
          },
          shapes: [
            {
              ty: 'gr',
              bm: 0,
              hd: false,
              mn: 'ADBE Vector Group',
              nm: 'Ellipse 1',
              ix: 1,
              cix: 2,
              np: 3,
              it: [
                {
                  ty: 'el',
                  bm: 0,
                  hd: false,
                  mn: 'ADBE Vector Shape - Ellipse',
                  nm: 'Ellipse Path 1',
                  d: 1,
                  p: { a: 0, k: [0, 0], ix: 3 },
                  s: { a: 0, k: [64, 64], ix: 2 },
                },
                {
                  ty: 'fl',
                  bm: 0,
                  hd: false,
                  mn: 'ADBE Vector Graphic - Fill',
                  nm: 'Fill 1',
                  c: { a: 0, k: color, ix: 4 },
                  r: 1,
                  o: { a: 0, k: 100, ix: 5 },
                },
                {
                  ty: 'tr',
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  sk: { a: 0, k: 0, ix: 4 },
                  p: { a: 0, k: [0, 0], ix: 2 },
                  r: { a: 0, k: 0, ix: 6 },
                  sa: { a: 0, k: 0, ix: 5 },
                  o: { a: 0, k: 100, ix: 7 },
                },
              ],
            },
          ],
          ind: 2,
        },
      ],
      v: '5.7.0',
      fr: 24,
      op: 24,
      ip: 0,
      assets: [
        {
          nm: '',
          id: 'comp_0_dcf4d207-44cc-4b07-a995-b6aca93c84dc',
          layers: [
            {
              ty: 4,
              nm: 'check Outlines',
              sr: 1,
              st: 0,
              op: 378,
              ip: 0,
              hd: false,
              ddd: 0,
              bm: 0,
              hasMask: false,
              ao: 0,
              ks: {
                a: { a: 0, k: [32, 32, 0], ix: 1 },
                s: { a: 0, k: [100, 100, 100], ix: 6 },
                sk: { a: 0, k: 0 },
                p: { a: 0, k: [32, 32, 0], ix: 2 },
                r: { a: 0, k: 0, ix: 10 },
                sa: { a: 0, k: 0 },
                o: { a: 0, k: 100, ix: 11 },
              },
              shapes: [
                {
                  ty: 'gr',
                  bm: 0,
                  hd: false,
                  mn: 'ADBE Vector Group',
                  nm: 'Group 1',
                  ix: 1,
                  cix: 2,
                  np: 2,
                  it: [
                    {
                      ty: 'sh',
                      bm: 0,
                      hd: false,
                      mn: 'ADBE Vector Shape - Group',
                      nm: 'Path 1',
                      ix: 1,
                      d: 1,
                      ks: {
                        a: 0,
                        k: {
                          c: true,
                          i: [
                            [0, 0],
                            [0, 0],
                            [-0.623, -0.623],
                            [0, 0],
                            [0.623, -0.623],
                            [0, 0],
                            [0.622, 0.623],
                            [0, 0],
                            [-0.623, 0.623],
                            [0, 0],
                            [-0.623, -0.623],
                          ],
                          o: [
                            [0, 0],
                            [0.623, -0.623],
                            [0, 0],
                            [0.623, 0.624],
                            [0, 0],
                            [-0.623, 0.623],
                            [0, 0],
                            [-0.623, -0.622],
                            [0, 0],
                            [0.622, -0.623],
                            [0, 0],
                          ],
                          v: [
                            [-3.383, 0.564],
                            [7.894, -10.713],
                            [10.15, -10.713],
                            [13.533, -7.331],
                            [13.533, -5.075],
                            [-2.256, 10.713],
                            [-4.51, 10.713],
                            [-13.533, 1.691],
                            [-13.533, -0.564],
                            [-10.15, -3.947],
                            [-7.895, -3.947],
                          ],
                        },
                        ix: 2,
                      },
                    },
                    {
                      ty: 'fl',
                      bm: 0,
                      hd: false,
                      mn: 'ADBE Vector Graphic - Fill',
                      nm: 'Fill 1',
                      c: { a: 0, k: [1, 1, 1], ix: 4 },
                      r: 1,
                      o: { a: 0, k: 100, ix: 5 },
                    },
                    {
                      ty: 'tr',
                      a: { a: 0, k: [0, 0], ix: 1 },
                      s: { a: 0, k: [100, 100], ix: 3 },
                      sk: { a: 0, k: 0, ix: 4 },
                      p: { a: 0, k: [32.311, 31.701], ix: 2 },
                      r: { a: 0, k: 0, ix: 6 },
                      sa: { a: 0, k: 0, ix: 5 },
                      o: { a: 0, k: 100, ix: 7 },
                    },
                  ],
                },
              ],
              ind: 1,
            },
          ],
        },
      ],
    };
  }, [color]);
};

export default useGetLoaderSuccessJSON;
